import { useEffect,useState } from "react";
import type { FormEvent } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { createSubTask,deleteSubTask,deleteTask,getTask,updateSubTask,updateTask,type SubTask,type Task } from "../../api/task.api";
import type { TaskStatus } from "../../types/task";
import { useProjectRole } from "../../hooks/useProjectRole";
import { getProjectMembers } from "../../api/member.api";

const statuses:TaskStatus[]=["todo","in_progress","done"];
export default function TaskDetails(){
 const {projectId,taskId}=useParams<{projectId:string;taskId:string}>();const navigate=useNavigate();const {isProjectAdmin}=useProjectRole(projectId);
 const [task,setTask]=useState<Task|null>(null);const [subtasks,setSubtasks]=useState<SubTask[]>([]);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [status,setStatus]=useState<TaskStatus>("todo");const [subTitle,setSubTitle]=useState("");const [subAssignedTo,setSubAssignedTo]=useState("");const [assignedTo,setAssignedTo]=useState("");const [members,setMembers]=useState<import("../../api/member.api").ProjectMember[]>([]);const [error,setError]=useState("");
 const load=async()=>{if(!projectId||!taskId)return;try{const r=await getTask(projectId,taskId);const d=r.data??r;setTask(d);setTitle(d.title||"");setDescription(d.description||"");setStatus(d.status||"todo");setAssignedTo(typeof d.assignedTo==="object"&&d.assignedTo?d.assignedTo._id:"");setSubtasks(d.subtasks||[]);}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to load task");}};
 useEffect(()=>{void load();if(projectId)getProjectMembers(projectId).then(r=>setMembers(r.data??r)).catch(()=>setMembers([]));},[projectId,taskId]);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!projectId||!taskId)return;try{await updateTask(projectId,taskId,{title,description,status,...(assignedTo?{assignedTo}: {})});await load();}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to update task");}};
 const addSub=async(e:FormEvent)=>{e.preventDefault();if(!projectId||!taskId||!subTitle)return;try{await createSubTask(projectId,taskId,{title:subTitle,...(subAssignedTo?{assignedTo:subAssignedTo}: {})});setSubTitle("");setSubAssignedTo("");await load();}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to create subtask");}};
 const toggle=async(s:SubTask)=>{if(!projectId)return;try{const completed=!s.isCompleted;await updateSubTask(projectId,s._id,{isCompleted:completed});await load();}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to update subtask");}};
 const removeSub=async(id:string)=>{if(!projectId||!window.confirm("Delete this subtask?"))return;try{await deleteSubTask(projectId,id);await load();}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to delete subtask");}};
 const removeTask=async()=>{if(!projectId||!taskId||!window.confirm("Delete this task?"))return;try{await deleteTask(projectId,taskId);navigate(`/projects/${projectId}/tasks`);}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||"Unable to delete task");}};
 if(!task)return <main className="page"><Link to={`/projects/${projectId}/tasks`}>← Tasks</Link>{error?<div className="error">{error}</div>:<p>Loading task...</p>}</main>;
 return <main className="page"><Link to={`/projects/${projectId}/tasks`}>← Tasks</Link>{error&&<div className="error">{error}</div>}<div className="task-detail"><div className="task-detail-header"><div><span className={`status-badge status-${task.status}`}>{task.status.replace("_"," ")}</span><h1>{task.title}</h1></div>{isProjectAdmin&&<button className="danger-button" onClick={()=>void removeTask()}>Delete task</button>}</div>
 {isProjectAdmin?<form className="task-form" onSubmit={save}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5}/></label><label>Assignee<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Unassigned</option>{members.map(m=>m.user&&<option key={m.user._id} value={m.user._id}>{m.user.fullName||m.user.username||m.user.email}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as TaskStatus)}>{statuses.map(s=><option key={s} value={s}>{s.replace("_"," ")}</option>)}</select></label><button>Save changes</button></form>:<div><p>{task.description||"No description"}</p><p>Status: {task.status.replace("_"," ")}</p></div>}
 <section className="subtask-section"><h2>Subtasks</h2>{isProjectAdmin&&<form className="subtask-form" onSubmit={addSub}><input placeholder="Subtask title" value={subTitle} onChange={e=>setSubTitle(e.target.value)} required/><select value={subAssignedTo} onChange={e=>setSubAssignedTo(e.target.value)}><option value="">Unassigned</option>{members.map(m=>m.user&&<option key={m.user._id} value={m.user._id}>{m.user.fullName||m.user.username||m.user.email}</option>)}</select><button>Add subtask</button></form>}{subtasks.length===0?<p>No subtasks.</p>:<div className="subtask-list">{subtasks.map(s=><div className="subtask-card" key={s._id}><label><input type="checkbox" checked={Boolean(s.isCompleted)} onChange={()=>void toggle(s)}/><span className={s.isCompleted?"completed":""}>{s.title}</span></label>{isProjectAdmin&&<button className="danger-button" onClick={()=>void removeSub(s._id)}>Delete</button>}</div>)}</div>}</section>
 </div></main>;
}
